[package]
name = "rbody"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
matfile = "0.4"
ndarray = "0.15.6"
bincode = "1.3.3"
egui = "0.22.0"
eframe = "0.22.0"
